### ISSUE TITLE
Say command help?

### ISSUE THREAD

**Issue by Mariogamerexpert** [mininmobile/discord.bat#3]
Okay, so I'm working on a say command but messagecontent includes the command name in it... how would I remove "saytest" from my bot's message when i type (prefix)saytest? Is there a way to port the message (without the command name) to a variable and then use that?

**Comment by mininmobile** [comment]
there is a working fix for this; don't use discord.bat

**Comment by Mariogamerexpert** [comment]
No other discord type works and glitch.me/uptime robot stopped working a while ago. Your creation is my only hope as of right now.
